const EVENTS = {
  DEVICE_CONNECT: "DEVICE_CONNECT",
  DEVICE_IS_CONNECTING: "DEVICE_IS_CONNECTING",
  DEVICE_IS_NOT_CONNECTING: "DEVICE_IS_NOT_CONNECTING",
  RECEIVE_HEART_DATA: "RECEIVE_HEART_DATA",
  HEART_DETECT_SUCCESS: "HEART_DETECT_SUCCESS",
  HEART_DETECT_FAILED: "HEART_DETECT_FAILED",
  DEVICE_DISCONNECTED: "DEVICE_DISCONNECTED",
  RECEIVE_OXYGEN_DATA: "RECEIVE_OXYGEN_DATA",
  DEVICE_FOUND: "DEVICE_FOUND",
  RECEIVE_OXYGEN_DATA: "RECEIVE_OXYGEN_DATA",
  RECEIVE_BP_DATA: "RECEIVE_BP_DATA",
  DEVICE_BATTER_LEVE_CHANGE: "DEVICE_BATTER_LEVE_CHANGE",
};

export default EVENTS;
